const TRANSLATIONS = {
  de: {
    'Address': 'Adresse',
    'Already Past': 'Schon vorbei',
    'Checkpoint hint': 'Checkpoint Hinweis',
    'Checkpoint location': 'Checkpoint Ort',
    'City': 'Stadt',
    'Coming Soon': 'Demnächst',
    'Country': 'Land',
    'Credits': 'Credits',
    'Date': 'Datum',
    'Download': 'Download',
    'Downloads': 'Downloads',
    'Error': 'Fehler',
    'Event type': 'Art des Events',
    'Events': 'Veranstaltungen',
    'Event in': 'Veranstaltung von',
    'Fair Booth': 'Messestand',
    'Festival': 'Festival',
    'Finish': 'Ziel',
    'Game': 'Spiel',
    'Games': 'Spiele',
    'Gathering point': 'Treffpunkt',
    'Home': 'Startseite',
    'Imprint': 'Impressum',
    'Journey': 'Journey',
    'lang': 'de',
    'Lecture': 'Vorlesung',
    'Link': 'Link',
    'Links': 'Links',
    'Media file': 'Mediendatei',
    'Media': 'Medien',
    'Meet': 'Treffen',
    'Meta: Description': 'Österreich\'s erste Initiative für das Spielen im öffentlichen Raum; Wir organisieren die Journey Vienna, Urban Game Clinic und vieles mehr!',
    'Next Week': 'Nächste Woche',
    'Notification: Calendar search instructions': 'Tipp: Mit Suchbegriffen wie "2014", "2016-2017", "November 2014 - Februar 2015", "21. April 2015", usw. kannst du eine intelligente Kalendersuche durchführen.',
    'Notification: Calendar search performed': 'Zusätzlich zur regulären text-basierten Suche wude auch eine intelligente Kalenderabfrage durchgeführt.',
    'Notification: Click to copy': 'Klick zum kopieren',
    'Notification: Copied to clipboard': 'Ins Clipboard kopiert',
    'Notification: Search length requirement': 'Bitte gib für eine Suche mindestens 3 Buchstaben ein.',
    'Panel Discussion': 'Podiumsdikussion',
    'Play': 'Spiel',
    'Playtest': 'Playtest',
    'play:vienna': 'play:vienna',
    'Results for': 'Ergebnisse für',
    'Search': 'Suche',
    'Select a game': 'Wähle ein Spiel',
    'Select a journey': 'Wähle eine Journey',
    'Select a page': 'Wähle eine Seite',
    'Select a year': 'Wähle ein Jahr',
    'Share': 'Teilen',
    'Start': 'Start',
    'Start time': 'Startzeit',
    'Talk': 'Vortrag',
    'Text': 'Text',
    'This page does not exist': 'Diese Seite existiert nicht.',
    'This Week': 'Diese Woche',
    'Title': 'Titel',
    'Tooltip: Facebook': 'Neuigkeiten, Fotos und Events von uns auf Facebook',
    'Tooltip: Flickr': 'Flickr Fotos aus der Community zu play:vienna',
    'Tooltip: Imprint': 'Impressum und Kontaktinformation',
    'Tooltip: Instagram': 'Unser Instagram Feed',
    'Tooltip: Language': 'Switch to the english site',
    'Tooltip: Newsletter': 'Melde dich für unseren Newsletter an',
    'Tooltip: Twitter': 'Unser play:vienna Twitter Feed',
    'Venue Link': 'Veranstaltungsort Link',
    'Venue': 'Veranstaltungsort',
    'Workshop': 'Workshop',
    'Year': 'Jahr'
  },
  en: {
    'Address': 'Address',
    'Already Past': 'Already Past',
    'Checkpoint hint': 'Checkpoint hint',
    'Checkpoint location': 'Checkpoint location',
    'City': 'City',
    'Coming Soon': 'Coming Soon',
    'Country': 'Country',
    'Credits': 'Credits',
    'Date': 'Date',
    'Download': 'Download',
    'Downloads': 'Downloads',
    'Error': 'Error',
    'Event type': 'Event type',
    'Events': 'Events',
    'Event in': 'Event in',
    'Fair Booth': 'Fair Booth',
    'Festival': 'Festival',
    'Finish': 'Finish',
    'Game': 'Game',
    'Games': 'Games',
    'Gathering point': 'Gathering point',
    'Home': 'Home',
    'Imprint': 'Imprint',
    'Journey': 'Journey',
    'lang': 'en',
    'Lecture': 'Lecture',
    'Link': 'Link',
    'Links': 'Links',
    'Media file': 'Media file',
    'Media': 'Media',
    'Meet': 'Meet',
    'Meta: Description': 'Austria\'s first initiative for games in public space; We organize the Journey Vienna, Urban Game Clinic and much more!',
    'Next Week': 'Next Week',
    'Notification: Calendar search instructions': 'Hint: You can perform a smart calendar search with queries like "2014", "2016-2017", "November 2012 - February 2013", "21st April 2015", and so on.',
    'Notification: Calendar search performed': 'In addition to the regular text-based search, a smart calendar lookup was additionally performed.',
    'Notification: Click to copy': 'Click to copy',
    'Notification: Copied to clipboard': 'Copied to your clipboard',
    'Notification: Search length requirement': 'Please provide at least 3 characters for a search.',
    'Panel Discussion': 'Panel Discussion',
    'Play': 'Play',
    'play:vienna': 'play:vienna',
    'Playtest': 'Playtest',
    'Results for': 'Results for',
    'Search': 'Search',
    'Select a game': 'Select a game',
    'Select a journey': 'Select a journey',
    'Select a page': 'Select a page',
    'Select a year': 'Select a year',
    'Share': 'Share',
    'Start': 'Start',
    'Start time': 'Start time',
    'Talk': 'Talk',
    'Text': 'Text',
    'This page does not exist': 'This page does not exist.',
    'This Week': 'This Week',
    'Title': 'Title',
    'Tooltip: Facebook': 'News, photos and events by us on facebook',
    'Tooltip: Flickr': 'Flickr photos from the community about play:vienna',
    'Tooltip: Imprint': 'Imprint and contact information',
    'Tooltip: Instagram': 'Our instagram feed',
    'Tooltip: Language': 'Zur deutschen Seite wechseln',
    'Tooltip: Newsletter': 'Sign up for our newsletter',
    'Tooltip: Twitter': 'Our play:vienna twitter feed',
    'Venue Link': 'Venue link',
    'Venue': 'Venue',
    'Workshop': 'Workshop',
    'Year': 'Year'
  }
};

module.exports = (context, string) => {
  const locale = context.locale;

  if(TRANSLATIONS[locale].hasOwnProperty(string)) {
    return TRANSLATIONS[locale][string];
  } else {
    throw `Unavailable translation for '${string}' in locale '${locale}' requested`;
  }
};
